- name: Setup Robohsop Project
  hosts: all
  become: yes
  tasks:
    - name: Import frontend
      ansible.builtin.import_role:
        name: frontend
      tags: frontend
      when: APP == "frontend"

    - name: Import catalogue
      ansible.builtin.import_role:
        name: catalogue
        tags: ctalogue
      when: APP == "catalogue"

