filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/{{COMPONENT}}.log

    json.keys_under_root: true
    json.message_key: msg



filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
output.elasticsearch:
  #hosts: ["localhost:9200"]  #ip is the elasticsearch(ELK) private address
  hosts: ["172.31.66.147:9200"]
  index: "{{COMPONENT}}-%{+yyyy.MM.dd}"

setup.template.name: "{{COMPONENT}}"
setup.template.pattern: "{{COMPONENT}}-*"


