- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download {{ COMPONENT }} Component
  ansible.builtin.include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{COMPONENT}}
    APP_USER: roboshop

- name: Install NodeJS Modules
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop

#- name: Download {{ APP }} Componenet
#  include_role:
#    name: common
#    tasks_from: curl_download
#  vars:
#    EXTRACT_DIR: /home/roboshop/{{APP}}
#    APP_USER: roboshop

